---
jobs:
- name: build
  plan:
  - get: librarian
    trigger: true
  - get: resource-gist-dev
  - task: build-task
    file: librarian/ci/build/task.yml
  - put: resource-gist-dev
    params:
      repository: updated-gist
      force: true
- name: push-to-dev
  plan:
  - get: librarian
  - get: resource-gist-dev
    trigger: true
    passed:
      - build
  - put: cf
    params:
      command: zero-downtime-push
      space: playground
      manifest: librarian/manifest.yml
      path: resource-gist-dev/librarian.zip
      current_app_name: librarian
  - put: resource-gist-staging
    params:
      repository: resource-gist-dev
      force: true
- name: push-to-staging
  plan:
  - get: librarian
  - get: resource-gist-staging
    trigger: false
    passed:
      - push-to-dev
  - put: cf
    params:
      command: zero-downtime-push
      space: Staging
      manifest: librarian/manifest-staging.yml
      path: resource-gist-staging/librarian.zip
      current_app_name: librarian
  - put: resource-gist-prod
    params:
      repository: resource-gist-staging
      force: true
- name: push-to-prod
  plan:
  - get: librarian
  - get: resource-gist-prod
    trigger: false
    passed:
      - push-to-staging
  - put: cf
    params:
      command: zero-downtime-push
      space: Production
      manifest: librarian/manifest-prod.yml
      path: resource-gist-prod/librarian.zip
      current_app_name: librarian

resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
- name: cf
  type: cf-cli-resource
  source:
    api: https://api.run.pcfone.io
    username: ((cf_username))
    password: ((cf_password))
    org: pivot-acourter

- name: resource-gist-dev
  type: git
  source:
    uri: git@gist.github.com:05f565fea7844508e96c1b89811c09a9.git
    branch: master
    private_key: ((git_key))

- name: resource-gist-prod
  type: git
  source:
    uri: git@gist.github.com:99f96577082374a538a1f766418d5644.git
    branch: master
    private_key: ((git_key))

- name: resource-gist-staging
  type: git
  source:
    uri: git@gist.github.com:0b71833f027e4a7cc5a831c6d08b46bf.git
    branch: master
    private_key: ((git_key))

- name: librarian
  type: git
  source:
    uri:  ((git_uri))
    branch: master
    private_key: ((git_key))