"""empty message

Revision ID: 6448b65b6c98
Revises: e2e24d723f5c
Create Date: 2019-01-09 10:05:29.158605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6448b65b6c98'
down_revision = 'e2e24d723f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('authors', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'authors')
    # ### end Alembic commands ###
