"""empty message

Revision ID: d509686f08ac
Revises: 6448b65b6c98
Create Date: 2019-01-09 10:20:19.839637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd509686f08ac'
down_revision = '6448b65b6c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('imageLink', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'imageLink')
    # ### end Alembic commands ###
