"""empty message

Revision ID: e2e24d723f5c
Revises: b60608a3f887
Create Date: 2019-01-08 15:07:35.857762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e24d723f5c'
down_revision = 'b60608a3f887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('office_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'offices', ['office_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'office_id')
    op.drop_table('offices')
    # ### end Alembic commands ###
