"""empty message

Revision ID: f684137efae5
Revises: 
Create Date: 2019-01-13 20:48:07.482146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f684137efae5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offices'))
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('isbn', sa.String(length=80), nullable=True),
    sa.Column('authors', sa.String(length=80), nullable=True),
    sa.Column('imageLink', sa.String(length=2000), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], name=op.f('fk_books_office_id_offices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('offices')
    # ### end Alembic commands ###
